.libPaths(c("G:/CSIEM/1.8.0/csiem-marvl/rayshader/rlib/4.4", .libPaths()))
suppressMessages({ library(rayshader); library(raster) })
dem <- raster_to_matrix(raster("data/dem_coarse_fixed.tif"))
sal <- raster_to_matrix(raster("data/sal_bottom/sal_059.tif"))
nr <- nrow(sal); nc <- ncol(sal)
water <- dem < 0
fin <- !is.na(sal)
frac_on_water <- function(mask) round(100*mean(water[mask]), 1)
cat("salt cells total:", sum(fin), "\n")
cat("asis     % on water:", frac_on_water(fin), "\n")
cat("flipUD   % on water:", frac_on_water(fin[nr:1, ]), "\n")
cat("flipLR   % on water:", frac_on_water(fin[, nc:1]), "\n")
cat("flipBOTH % on water:", frac_on_water(fin[nr:1, nc:1]), "\n")
cat("transpose? dim sal", nr, nc, " dim dem", nrow(dem), ncol(dem), "\n")
