.libPaths(c("G:/CSIEM/1.8.0/csiem-marvl/rayshader/rlib/4.4", .libPaths()))
suppressMessages({ library(rayshader); library(raster) })
r <- raster("data/dem_coarse_fixed.tif")
A  <- raster::as.matrix(r)            # TRUE north-up: A[1,]=north edge, A[,1]=west edge (847x419)
rt <- raster_to_matrix(r)             # what rayshader uses (419x847)
B  <- t(rt)                           # my proposed fix (847x419)
cat("dim A (truth):", dim(A), " dim B=t(rtm):", dim(B), "\n")
chk <- function(name, M) if(identical(dim(M),dim(A))) cat(sprintf("%-14s max|diff|=%.4f\n", name, max(abs(M-A),na.rm=TRUE)))
chk("t(rtm) asis", B)
chk("t(rtm) flipUD", B[nrow(B):1, ])
chk("t(rtm) flipLR", B[, ncol(B):1])
chk("t(rtm) flip180", B[nrow(B):1, ncol(B):1])
